# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
app-dir: ~/project
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
orbs:
  node: circleci/node@4.7.0

jobs:
  say-hello:
    # Specify the execution environment.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  npm-install:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - node/install:
          #version: '6.15.14'
          lts: true 
          node-install-dir: ~/project/src
      - run:
          command: npm start

  npm-start:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout
      - run: 
          name: "npmstart"
          command: npm start

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
  npm-install-workflow:
    jobs:
      - npm-install 
      #- npm-start  
  #npm-start-workflow:
  #   jobs:
  #    - npm-start
  